### ISSUE TITLE
missing market_cap and zero total_volume

### ISSUE THREAD

**Issue by waynelapierre** [next-game-solutions/geckor#44]
On 2017-04-02, market_cap is missing for bitcoin and ethereum. Also, when total_volume is zero, how is the price determined? 
 

```
crypto_top5 <- coin_history(c("bitcoin", "ethereum", "binancecoin", "ripple", "cardano"), 
                            vs_currency = "usd", days = "max")

```

**Comment by next-game-solutions** [comment]
The `geckor` package is just an interface for the CoinGecko API and, unfortunately, we cannot control what data are being returned by that API and how certain metrics are calculated. For further information please refer to their official documentation or contact their support representatives.
