### ISSUE TITLE
Package removed from CRAN

### ISSUE THREAD

**Issue by waynelapierre** [next-game-solutions/geckor#51]
https://cran.r-project.org/web/packages/geckor/index.html

**Comment by next-game-solutions** [comment]
Yes, as per README:

"As of v0.3.0, geckor is no longer published on CRAN."

**Comment by waynelapierre** [comment]
My bad, didn't notice that. Do you plan to bring it back to CRAN? I find it a great package.

**Comment by next-game-solutions** [comment]
> My bad, didn't notice that. Do you plan to bring it back to CRAN? I find it a great package.

This really depends on CoinGecko. They've made their free API almost unusable and because of that, unfortunately, it doesn't make much sense at this point to provide the same level of support and maintenance for this package as before (incl. having it on CRAN).
